### ISSUE TITLE
Disabled by default?

### ISSUE THREAD

**Issue by forrestab** [brandon-barker/angular-floatThead#11]
Just wondering, is this by design? I recently upgraded to the latest version and the previous version I was on did not have the `float-thead-enabled` property. Since upgrading the directive appears to be defaulted to disabled, which means I must add another property with a static value of `true` (I am not currently using a toggle feature) in order to get it to work.

**Comment by geraldhumphries** [comment]
Definitely broken in the current release, but I tried `master` and there's no issue there. So it just needs to be released.

**Comment by forrestab** [comment]
Yeah, I just noticed that myself, was testing to make sure before I updated this issue. 

There does appear to be a minification issue when the `controller` is created in the `master` branch source (at least this is the case for Asp.Net bundling and minification).

**Comment by brandon-barker** [comment]
Hi guys @forrestab @geraldhumphries , sorry for the late reply on this. This should now be fixed in #12 - thanks to @nhorvath. I've pushed a new tag up so bower should reflect the update soon
