### ISSUE TITLE
jQuery(...).floatThead is not a function

### ISSUE THREAD

**Issue by TAMMENY** [brandon-barker/angular-floatThead#13]
Hi, i had some trouble in using angular-floatThead. I follow the README.md and the console throw jQuery(...).floatThead is not a function, how should i do ?

Angular version: "1.5.5"

**Comment by brandon-barker** [comment]
Hi there

Have you installed the main floatThead library first? You need to do so via https://github.com/mkoryak/floatThead

**Comment by TAMMENY** [comment]
@brandon-barker 
Sorry, I missed the main floatThead library, but there are another error was thrown after i introduced the main library：
`VM6465:27 jQuery.floatThead: option 'useAbsolutePositioning' has been removed in v1.3.0, use position:'auto' instead. See docs for more info: http://mkoryak.github.io/floatThead/#options`
and
`jQuery.floatThead: option 'scrollingTop' has been renamed to 'top' in v1.3.0. See docs for more info: http://mkoryak.github.io/floatThead/#options`
Is there anything missing ?

**Comment by TAMMENY** [comment]
I made it, anyway, thank you.
