### ISSUE TITLE
Release version?

### ISSUE THREAD

**Issue by SlippySken** [brandon-barker/angular-floatThead#16]
Hey there,
we need the fix for the minification issues in commit ec372afcb3e43f23b9207e610d45616607e9ec85 for our project. Maybe you can make a new release with this little change?
I want to avoid forking and adding the project to our project.

And it is planed to release this little library on npm?

Regards,
Markus

**Comment by brandon-barker** [comment]
Hi there,

I've pushed up a new tag (v0.1.2) which should propagate on bower shortly.

Thanks for logging the issue!

Regards,
Brandon

**Comment by SlippySken** [comment]
Yay, thank you :)
