### ISSUE TITLE
How to use this with dynamic columns?

### ISSUE THREAD

**Issue by Mafti** [brandon-barker/angular-floatThead#7]
Hi,

It works like a charm for most of the tables.
However I have 1 table that is hidden first.
then people can add columns. for some reason the floatHeader does not work then.

**Comment by brandon-barker** [comment]
Hi,

If you specify an ng-model the directive will watch for changes and then call 'reflow' on the floatThead library, this should trigger an update.

If that doesn't work, could you please put up a plunker and I'll look into it for you?
