### ISSUE TITLE
option to init plugin after watched expression becomes true

### ISSUE THREAD

**Issue by mkoryak** [brandon-barker/angular-floatThead#8]
Someone  had a problem where he was using this plugin to init on a large table built with ng-repeat using position: 'fixed' option. The problem was that the plugin ran before ngrepeat finished building the table causing you to see 2 headers. 

I propose adding another option `init-on='somethingThatWillBecomeTrue'` or something

**Comment by brandon-barker** [comment]
Hi @mkoryak 

Great idea, thanks! I will investigate and work on an update when I get home from work today :+1:
